src/export/urls.py
from django.urls import path
from . import views

app_name = "export"

urlpatterns = [
    path('', views.category_form, name="category-form"),
    path('list/<int:category_pk>', views.list_zadaci, name="list"),
]

src/import_json/urls.py
from django.urls import path
from . import views

app_name = "import_json"

urlpatterns = [
    path('', views.import_json, name="json"),
    path('list/save/', views.save_questions, name="save-questions"),
    path('list/<str:fn>/', views.list_form, name="list-form"),
    path('detail/<int:pk>', views.MoodleZadatakDetailView.as_view(), name="zadatak-detail")
]

src/rm2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('import/', include("import_json.urls")),
    path('export/', include("export.urls")),
    path('summernote/', include("django_summernote.urls")),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RM2 Kolokviji</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <span class="navbar-brand mb-0 h1">RM2 Kolokviji</span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-navbar" aria-controls="main-navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="main-navbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Početna <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'import_json:json' %}">Import JSON</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'export:category-form' %}">Export</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block messages %}
    {% include "messages.html" %}
    {% endblock messages %}
    
    {% block body %}
    {% endblock body %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}


{% block body %}

<div class="container pt-2">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="h2">Popis pitanja</h2>
        </div>
    </div>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th><th>Naziv</th><th>Ocjena</th><th>Kategorija</th><th></th>
            </tr>
        </thead>
        <tbody>
            {% for zadatak in zadaci %}
            <tr style="line-height:2.5;">
                <td>{{ zadatak.id }}</td>
                <td>{{ zadatak.name }}</td>
                <td>{{ zadatak.defaultgrade }}</td>
                <td>{{ zadatak.moodle_kategorija.category_name }}</td>
                <td><a class="btn btn-secondary" href="{{ zadatak.get_absolute_url }}">Prikaz</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock body %}

src/templates/messages.html
<div class="container">
{% if messages %}
    <div class="row">
        {% for message in messages %}
        <div class="col-lg-12 {{ message.tags }}">
            <p class="h4 mb-1 p-2 text-light">{{ message }}</p>
        {% endfor %}
        </div>
        </div>
{% endif %}
</div>