src/import_json/urls.py
from django.urls import path
from . import views

app_name = "import_json"

urlpatterns = [
    path('', views.import_json, name="json"),
    path('list/save/', views.save_questions, name="save-questions"),
    path('list/<str:fn>/', views.list_form, name="list-form"),
    path('detail/<int:pk>', views.MoodleZadatakDetailView.as_view(), name="zadatak-detail")
]

src/rm2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('import/', include("import_json.urls")),
    path('export/', include("export.urls")),
    path('summernote/', include("django_summernote.urls")),
]

src/import_json/models.py
from django.db import models
from django.urls import reverse


COURSE_CHOICES = (
    ('RM1', 'Računalne Mreže 1'),
    ('RM2', 'Računalne Mreže 2'),
)

CATEGORY_CHOICES = (
    (1, '1. kolokvij'),
    (2, '2. kolokvij'),
)

ANSWERNUMBERING_CHOICES = (
    ('abc', 'a., b., c., ...'),
    ('ABC', 'A., B., C., ...'),
    ('123', '1., 2., 3., ...'),
    ('iii', 'i., ii., iii., ...'),
    ('III', 'I., II., III., ...'),
)

FRACTION_CHOICES = (
    (0, 'None'),
    (1, '100'),
    (2, '90'),
    (3, '83.33333'),
    (4, '80'),
    (5, '75'),
    (6, '70'),
    (7, '66.66667'),
    (8, '60'),
    (9, '50'),
    (10, '40'),
    (11, '33.33333'),
    (12, '30'),
    (13, '25'),
    (14, '20'),
    (15, '16.66667'),
    (16, '14.28571'),
    (17, '12.5'),
    (18, '11.11111'),
    (19, '10'),
    (20, '5'),
    (21, '-100'),
    (22, '-90'),
    (23, '-83.33333'),
    (24, '-80'),
    (25, '-75'),
    (26, '-70'),
    (27, '-66.66667'),
    (28, '-60'),
    (20, '-50'),
    (30, '-40'),
    (31, '-33.33333'),
    (32, '-30'),
    (33, '-25'),
    (34, '-20'),
    (35, '-16.66667'),
    (36, '-14.28571'),
    (37, '-12.5'),
    (38, '-11.11111'),
    (39, '-10'),
    (40, '-5'),
)

PENALTY_CHOICES = (
    (0, '0'),
    (1, '100'),
    (2, '50'),
    (3, '33.33333'),
    (4, '25'),
    (5, '20'),
    (5, '10'),
)

TYPE_CHOICES = (
    (0, 'multichoice'),
    (1, 'truefalse'),
    (2, 'shortanswer'),
    (3, 'matching'),
    (4, 'cloze'),
    (5, 'essay'),
    (6, 'numerical'),
    (7, 'description')
)

SINGLE_CHOICES = (
    (0, 'Više točnih odgovora'),
    (1, 'Jedan točan odgovor'),
)


class MoodleZadatak(models.Model):

    name                = models.CharField("Naziv pitanja", max_length=255)
    questiontext        = models.TextField("Tekst pitanja")
    defaultgrade        = models.FloatField("Ocjena za pitanje")
    generalfeedback     = models.TextField("Napomena", null=True, blank=True, help_text="Napomena o pitanju namijenjena studentu nakon prikaza ocjene")
    idnumber            = models.CharField("Moodle ID", null=True, blank=True, help_text="Moodleova oznaka za ID pitanja", max_length=50)
    single              = models.BooleanField("Jedan ili više točnih odgovora", choices=SINGLE_CHOICES, default=1)
    shuffleanswers      = models.BooleanField("Mješanje poretka odgovora", default=1)
    answernumbering     = models.CharField("Oznake odgovora", default=ANSWERNUMBERING_CHOICES[0][0], choices=ANSWERNUMBERING_CHOICES, help_text="Oznaka za ispis odgovora u sustavu Moodle", max_length=3)
    penalty             = models.FloatField("Penal za netočni pokušaj", default=PENALTY_CHOICES[0][0], choices=PENALTY_CHOICES)

    type                = models.IntegerField("Tip Moodle zadataka", default=TYPE_CHOICES[0][0], choices=TYPE_CHOICES)
    moodle_kategorija   = models.ForeignKey("import_json.MoodleKategorija", verbose_name="moodle_kategorija", on_delete=models.CASCADE)

    correctfeedback     = models.CharField("Napomena - Točan odgovor", null=True, blank=True, max_length=50)
    incorrectfeedback   = models.CharField("Napomena - Netočan odgovor", null=True, blank=True, max_length=50)   
    partiallycorrectfeedback = models.CharField("Napomena - Nepotpun odgovor", null=True, blank=True, max_length=50)


    class Meta:
        verbose_name = "Moodle Zadatak"
        verbose_name_plural = "Moodle Zadatci"

    def __str__(self):
        return "<MoodleZadatak: name={0} grade={1}>".format(self.name, self.defaultgrade)

    def get_absolute_url(self):
        return reverse("import_json:zadatak-detail", kwargs={"pk": self.pk})


class MoodleOdgovor(models.Model):

    name    = models.CharField("Odgovor", max_length=255)
    correct = models.BooleanField("Točan odgovor", default=False)

    feedback            = models.TextField("Napomena", null=True, blank=True, help_text="Napomena o individualnom odgovoru namijenjena studentu nakon prikaza ocjene")
    fraction_correct    = models.FloatField("Udio točnog odgovora u bodovanju", choices=FRACTION_CHOICES)

    moodle_zadatak      = models.ForeignKey("import_json.MoodleZadatak", verbose_name="moodle_zadatak", on_delete=models.CASCADE)

    @property
    def get_fraction_correct(self):
        if self.fraction_correct == 0:
            return 0
        else:
            return self.get_fraction_correct_display()


    class Meta:
        verbose_name = "Moodle Odgovor"
        verbose_name_plural = "Moodle Odgovori"

    def __str__(self):
        return self.name



class MoodleKolegij(models.Model):

    course_name = models.CharField("Naziv kolegija", choices=COURSE_CHOICES, help_text="Naziv kolegija u sustavu Moodle", max_length=3)

    class Meta:
        verbose_name = "Moodle Kolegij"
        verbose_name_plural = "Moodle Kolegiji"

    def __str__(self):
        return self.course_name

    def get_absolute_url(self):
        return reverse("import_json:kolegij-detail", kwargs={"pk": self.pk})


class MoodleKategorija(models.Model):

    category_name  = models.CharField("Naziv kategorije", max_length=64)
    moodle_kolegij = models.ForeignKey("import_json.MoodleKolegij", verbose_name="moodle_kolegij", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Moodle Kategorija"
        verbose_name_plural = "Moodle Kategorije"

    def __str__(self):
        return "{0} - {1}".format(self.moodle_kolegij, self.category_name)

src/import_json/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import MoodleKolegij, MoodleKategorija, MoodleZadatak, MoodleOdgovor

class ImportJsonForm(forms.Form):
    json_file = forms.FileField(label="JSON datoteka", max_length=255, required=True, widget=forms.FileInput(attrs={'class': 'form-control'}))

class MoodleKolegijForm(forms.ModelForm):

    def clean(self):
        cleaned_data = super().clean()
        course_name = cleaned_data.get('course_name')

        matching_courses = MoodleKolegij.objects.filter(course_name=course_name)
        if self.instance:
            matching_courses = matching_courses.exclude(pk=self.instance.pk)
        if matching_courses.exists():
            msg = "Moodle Kolegij: Kolegij već postoji"
            raise ValidationError(msg)
        else:
            return self.cleaned_data


    class Meta:
        model = MoodleKolegij
        fields = ('course_name',)
        widgets = {
            'course_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

class MoodleKategorijaForm(forms.ModelForm):

    def clean(self):
        cleaned_data = super().clean()
        category_name = cleaned_data.get('category_name')

        matching_categories = MoodleKategorija.objects.filter(category_name=category_name)
        if self.instance:
            matching_categories = matching_categories.exclude(pk=self.instance.pk)
        if matching_categories.exists():
            msg = "Moodle Kategorija: Kategorija već postoji"
            raise ValidationError(msg)
        else:
            return self.cleaned_data


    class Meta:
        model = MoodleKategorija
        fields = ('category_name',)
        widgets = {
            'category_name': forms.TextInput(attrs={'class': 'form-control'}),
        }



class MoodleZadatakForm(forms.ModelForm):

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')

        matching_zadaci = MoodleZadatak.objects.filter(name=name)
        if self.instance:
            matching_zadaci = matching_zadaci.exclude(pk=self.instance.pk)
        if matching_zadaci.exists():
            msg = "Moodle Zadatak: Zadatak već postoji"
            raise ValidationError(msg)
        else:
            return self.cleaned_data

    
    class Meta:
        model = MoodleZadatak
        fields = (
            'name',
            'questiontext',
            'defaultgrade',
            'idnumber',
            'single',
            'shuffleanswers',
            'answernumbering',
            'generalfeedback',
            'penalty',
            'type',
            'correctfeedback',
            'incorrectfeedback',
            'partiallycorrectfeedback'
        )

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'questiontext': forms.Textarea(attrs={'class': 'form-control'}),
            'defaultgrade': forms.NumberInput(attrs={'class': 'form-control'}),
            'generalfeedback': forms.Textarea(attrs={'class': 'form-control'}),
            'idnumber': forms.TextInput(attrs={'class': 'form-control'}),
            'single': forms.Select(attrs={'class': 'custom-select'}),
            'shuffleanswers': forms.CheckboxInput(attrs={'class': 'form-check'}),
            'answernumbering': forms.Select(attrs={'class': 'custom-select'}),
            'penalty': forms.Select(attrs={'class': 'custom-select'}),
            'type': forms.Select(attrs={'class': 'custom-select'}),
            'correctfeedback': forms.TextInput(attrs={'class': 'form-control'}),
            'incorrectfeedback': forms.TextInput(attrs={'class': 'form-control'}),
            'partiallycorrectfeedback': forms.TextInput(attrs={'class': 'form-control'})
        }


class MoodleOdgovorForm(forms.ModelForm):
    moodle_zadatak_id = forms.IntegerField(label="ID - Moodle Zadatak", required=False, widget=forms.HiddenInput())
    
    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        moodle_zadatak_id = cleaned_data.get('moodle_zadatak_id')

        matching_odgovori = MoodleOdgovor.objects.filter(name=name, moodle_zadatak_id=moodle_zadatak_id)
        if self.instance:
            matching_odgovori = matching_odgovori.exclude(pk=self.instance.pk)
        if matching_odgovori.exists():
            msg = "Moodle Odgovor: Odgovor već postoji"
            raise ValidationError(msg)
        else:
            return self.cleaned_data

    class Meta:
        model = MoodleOdgovor
        fields = (
            'name',
            'correct',
            'feedback',
            'fraction_correct',
            'moodle_zadatak_id'
        )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'correct': forms.CheckboxInput(attrs={'class': 'form-check'}),
            'feedback': forms.Textarea(attrs={'class': 'form-control'}),
            'fraction_correct': forms.Select(attrs={'class': 'custom-select'})
        }

src/import_json/views.py
from django.shortcuts import render, redirect, reverse
from django.conf import settings
from django.contrib import messages
from django.views import generic
from . import utils, validate
from .models import MoodleKolegij, MoodleKategorija, MoodleZadatak
from .forms import ImportJsonForm, MoodleKolegijForm, MoodleKategorijaForm, MoodleZadatakForm, MoodleOdgovorForm

from datetime import date
import json
import os


def import_json(request):
    if request.method == "POST":
        form = ImportJsonForm(request.POST, request.FILES)
        if form.is_valid():
            json_file = request.FILES['json_file']

            try:
                dictionary = validate.validate_uploaded_file(json_file)
            except (ValueError, TypeError, KeyError) as e:
                messages.warning(request, e, extra_tags="bg-danger")
            else:
                dictionary = utils.transform_dictionary(dictionary)
                utils.write_dictionary(dictionary, json_file.name)

                messages.success(request, "Pitanja uspješno uvezena", extra_tags="bg-success")
                return redirect(reverse("import_json:list-form", kwargs={"fn": json_file.name}))
    else:
        form = ImportJsonForm()

    context = {
        'form': form
    }

    return render(request, "import_json/import_json_form.html", context)


def list_form(request, fn):
    today = date.today()
    today = date.strftime(today, "%Y-%m-%d")
    file_path = os.path.join(settings.MEDIA_ROOT, today, fn)

    with open(file_path, "r", encoding='utf-8') as f:
        json_string = f.read()
        dictionary = json.loads(json_string)

    kategorija_form = MoodleKategorijaForm(dictionary['kolegij'])
    kolegij_form = MoodleKolegijForm(dictionary['kolegij'])

    zadaci_forms = list()
    for zadatak in dictionary['zadaci']:
        zadatak_dict = dict()
        zadatak_dict['zadatak'] = MoodleZadatakForm(zadatak)

        rjesenje = {
            'name': zadatak['rjesenje'],
            'correct': 1,
            'feedback': "",
            'fraction_correct': zadatak['fraction_correct'],
            'moodle_zadatak_id': zadatak['idnumber']
        }
        zadatak_dict['odgovori'] = [MoodleOdgovorForm(rjesenje)]

        for odgovor in zadatak['odgovori']:
            odgovor = {
                'name': odgovor,
                'correct': 0,
                'feedback': "",
                'fraction_correct': zadatak['fraction_incorrect'],
                'moodle_zadatak_id': zadatak['idnumber']
            }
            zadatak_dict['odgovori'].append(MoodleOdgovorForm(odgovor))
        zadaci_forms.append(zadatak_dict)

    context = {
        'kategorija_form': kategorija_form,
        'kolegij_form': kolegij_form,
        'zadaci_forms': zadaci_forms
    }

    return render(request, "import_json/list_form.html", context)


def save_questions(request):
    if request.method == "POST":
        course_name = request.POST.get('course_name', None)
        category_name = request.POST.get('category_name', None)

        kategorija_form = MoodleKategorijaForm({'category_name': category_name})
        kolegij_form = MoodleKolegijForm({'course_name': course_name})

        if kolegij_form.is_valid():
            moodle_kolegij = kolegij_form.save()
        else:
            moodle_kolegij = MoodleKolegij.objects.get(course_name=course_name)

        if kategorija_form.is_valid():
            moodle_kategorija = kategorija_form.save(commit=False)
            moodle_kategorija.moodle_kolegij = moodle_kolegij
            moodle_kategorija.save()
        else:
            moodle_kategorija = MoodleKategorija.objects.get(category_name=category_name)

        i, j = 0, 0
        postojeci_zadaci = list()
        zadaci, odgovori = utils.parse_post(request.POST)
        for zadatak in zadaci:
            zadatak_form = MoodleZadatakForm(zadatak)

            if zadatak_form.is_valid():
                zadatak = zadatak_form.save(commit=False)
                zadatak.moodle_kategorija = moodle_kategorija
                zadatak.save()

                for odgovor in odgovori[zadatak.idnumber]:
                    odgovor_form = MoodleOdgovorForm(odgovor)
                    if odgovor_form.is_valid():
                        odg = odgovor_form.save(commit=False)
                        odg.moodle_zadatak = zadatak
                        odg.save()

                i += 1
            else:
                j += 1
                postojeci_zadaci.append(MoodleZadatak.objects.get(name=zadatak['name']))
        
        if i > 0:
            messages.success(request, "{0} zadataka uspješno spremljeno".format(i), extra_tags="bg-success")
        if j > 0:
            messages.warning(request, "{0} zadataka već postoji: {1}".format(j, postojeci_zadaci), extra_tags="bg-warning")    
        
        return redirect("home:index")


class MoodleZadatakDetailView(generic.DetailView):
    model = MoodleZadatak

src/templates/import_json/import_json_form.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="h2">Import JSON</h2>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">
            <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.errors }}
                    {{ form.as_table }}
                </table>
                <input type="submit" class="btn btn-primary" value="Spremi">
            </form>
        </div>
    </div>
</div>

{% endblock body %}

src/templates/import_json/list_form.html
{% extends 'base.html' %}

{% block body %}

<div class="container pt-3">
    <form method="post" action="{% url 'import_json:save-questions' %}">
    {% csrf_token %}
        <div class="card mb-3">
            <div class="card-header">
                <h3 class="h3">Informacije o kolegiju</h3>
            </div>
            <div class="card-body">
                {% for field in kolegij_form %}
                    <div class="pt-2">
                        {{ field.errors }}
                        <label for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
                        <br>
                        {% if field.help_text %}
                        <small class="help">{{ field.help_text|safe }}</small>
                        {% endif %}
                        {{ field }}
                    </div>
                {% endfor %}
                {% for field in kategorija_form %}
                    <div class="pt-2">
                        {{ field.errors }}
                        <label for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
                        <br>
                        {% if field.help_text %}
                        <small class="help">{{ field.help_text|safe }}</small>
                        {% endif %}
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
        </div>

    {% for zadatak_form in zadaci_forms %}
        <div class="card mb-2">
            <div class="card-header">
                <h3 class="h3">Pitanje {{ forloop.counter }}</h3>
            </div>
            <div id="{{ forloop.counter0 }}" class="card-body">
            {% for field in zadatak_form.zadatak %}
                <div class="pt-2 zadatak">
                    {{ field.errors }}
                    <label for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
                    <br>
                    {% if field.help_text %}
                    <small class="help">{{ field.help_text|safe }}</small>
                    {% endif %}
                    {{ field }}
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="card mb-2">
            <div class="card-header">
                <h3 class="h3">Odgovori</h3>
            </div>
            <div id="{{ forloop.counter0 }}" class="card-body">
            {% for odgovor in zadatak_form.odgovori %}
                <h4 class="h4">Odgovor {{ forloop.counter }}</h4>
                <div id="{{ forloop.counter0 }}" class="p-3">
                {% for field in odgovor %}
                    <div class="pt-2 odgovor">
                    {% if not field.is_hidden %}
                        {{ field.errors }}
                        <label for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
                        <br>
                        {% if field.help_text %}
                        <small class="help">{{ field.help_text|safe }}</small>
                        {% endif %}
                    {% endif %}
                        {{ field }}
                    </div>
                {% endfor %}
                </div>
            {% endfor %}
            </div>
        </div>
    {% endfor %}

        <input type="submit" class="btn btn-primary" value="Spremi">
    </form>
</div>

<script>

let zadaci = document.getElementsByClassName('zadatak');

for (let zadatak of zadaci) {
    console.log(zadatak.parentElement)
    for (let child of zadatak.children) {
        if (child.localName == "input" || child.localName == "select" || child.localName == "textarea") {
            child.name = child.name + "[" + zadatak.parentElement.id + "]";
        }
    }
}

let odgovori = document.getElementsByClassName('odgovor');

for (let odgovor of odgovori) {
    for (let child of odgovor.children) {
        if (child.localName == "input" || child.localName == "select" || child.localName == "textarea") {
            child.name = "odgovor_" + child.name + "[" + odgovor.parentElement.parentElement.id + "]" + "[" + odgovor.parentElement.id + "]";
        }
    }
}

</script>

{% endblock body %}

src/templates/import_json/moodlezadatak_detail.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="h2">Prikaz pitanja</h2>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="h3">Osnovne informacije</h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Naziv</th><td>{{ object.name }}</td>
                            </tr>
                            <tr>
                                <th>Tip pitanja</th><td>{{ object.get_type_display }}</td>
                            </tr>
                            <tr>
                                <th>Ocjena</th><td>{{ object.defaultgrade }}</td>
                            </tr>
                            <tr>
                                <th>Moodle ID</th><td>{{ object.idnumber }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="h3">Detalji o pitanju</h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Numeriranje odgovora</th><td>{{ object.get_answernumbering_display }}</td>
                            </tr>
                            <tr>
                                <th>Miješanje odgovora</th><td>{{ object.shuffleanswers }}</td>
                            </tr>
                            <tr>
                                <th>Broj točnih odgovora</th><td>{{ object.get_single_display }}</td>
                            </tr>
                            <tr>
                                <th>Penal za novi pokušaj</th><td>{{ object.get_penalty_display }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="h3">Pitanje i odgovori</h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Tekst pitanja</th><td>{{ object.questiontext }}</td>
                            </tr>
                        </tbody>
                    </table>
                    {% for odgovor in object.moodleodgovor_set.all %}
                    <div class="card mt-3">
                        <div class="card-header">
                            <h4 class="h4">Odgovor {{ forloop.counter }}</h4>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>Tekst odgovora</th><td>{{ odgovor.name }}</td>
                                    </tr>
                                    <tr>
                                        <th>Udio odgovora u ocjeni</th><td>{{ odgovor.get_fraction_correct }}%</td>
                                    </tr>
                                    <tr>
                                        <th>Napomena</th><td>{{ odgovor.feedback }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {% endfor %}
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Napomena - Točan odgovor</th><td>{{ object.correctfeedback }}</td>
                            </tr>
                            <tr>
                                <th>Napomena - Nepotpun odgovor</th><td>{{ object.partiallycorrectfeedback }}</td>
                            </tr>
                            <tr>
                                <th>Napomena - Netočan odgovor</th><td>{{ object.incorrectfeedback }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}